### ISSUE TITLE
关于其他平台的嵌入

### ISSUE THREAD

**Issue by LittleRobotRoad** [baidu-openmap-trace/web-demo-v3#1]
比如我使用java或者golang，怎么使用这些呢，之前我是直接把静态文件拷进去了

**Comment by dandandancj** [comment]
推荐先按照我写的教程，把前端的环境撘起来，整体走通。
之后你可以灵活的使用fis3来编译生成一套符合你们使用场景的代码。
说直白一点，就是这套DEMO代码下载完了是没法直接用的。需要按照文档，使用fis3编译出你需要的版本。
这么做可能起步慢一些，但是熟悉了整个DEMO的组成和fis3的使用后，就能方便的进行混淆压缩代码、统一修改url、编译不同的版本（线下调试、线下测试、线上正式等版本）等操作了。

**Comment by yangzhuanghhh** [comment]
先搭建起来能跑通，再慢慢移植到自己的项目中，明白了   这个版本注释很多，赞一个

**Comment by LittleRobotRoad** [comment]
好的，谢谢。
npm 下不动，cnpm 公司屏蔽了taobao域名。
蛋疼啊

**Comment by dandandancj** [comment]
https://cnpmjs.org/
这个镜像可用么?

**Comment by LittleRobotRoad** [comment]
dandandancj  太感谢你了，遇上屏蔽taobao域名的，很多阿里的东西直接被当成上班购物。
