### ISSUE TITLE
getdistance 查询轨迹里程  {"status":1,"message":"服务器内部错误"}

### ISSUE THREAD

**Issue by HuChundong** [baidu-openmap-trace/web-demo-v3#4]
1.官方文档 http://lbsyun.baidu.com/index.php?title=yingyan/api/v3/trackprocess#getdistance.E2.80.94.E2.80.94.E6.9F.A5.E8.AF.A2.E8.BD.A8.E8.BF.B9.E9.87.8C.E7.A8.8B，查询距离的URL写错了

2.查询距离的接口较高概率发生 {"status":1,"message":"服务器内部错误"}

**Comment by dandandancj** [comment]
已修复
