### ISSUE TITLE
您好，这项目是node.js，我之前的项目是javaee

### ISSUE THREAD

**Issue by EnnengYang** [baidu-openmap-trace/web-demo-v3#5]
这项目是node.js 原来的项目是javaee 请问一下怎么整合进原来的项目啊

**Comment by dandandancj** [comment]
这个项目其实并不是nodejs的，它是纯前端的项目
只是用了nodejs的module和npm作包管理。
你可以学习一下fis3的使用配置，把fis3编译后的项目文件放到您项目相应的路径。

**Comment by EnnengYang** [comment]
收到，多谢。
